# Generated by Django 4.1.7 on 2023-02-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.SmallIntegerField(),
        ),
    ]
